In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]
type(mylist)

list

In [4]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
np.zeros((2,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np_linspace = np.linspace(0,5,21)

In [10]:
# Matrix Identitas
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.random.rand(10)

array([0.75900905, 0.50114264, 0.00152656, 0.02044515, 0.730373  ,
       0.01098423, 0.06638993, 0.58410716, 0.13040646, 0.12459942])

In [12]:
np.random.randn(10)

array([-0.90663511, -2.28773983,  0.10519569,  0.14036693, -0.4459234 ,
       -0.15557126,  1.54607181, -0.14461232, -0.08013195, -1.31611082])

In [13]:
np.random.randn(5,2)

array([[-1.00900011,  0.80414798],
       [ 0.92770087, -0.12529826],
       [-0.31168543, -0.76307863],
       [ 0.44730392,  2.15731494],
       [ 0.0312122 ,  0.94675106]])

In [14]:
np.random.randint(0,101,10)

array([ 5,  3, 11,  3, 78,  7, 17, 54,  9, 37], dtype=int32)

In [15]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [16]:
np.random.seed(43)
np.random.rand(5)

array([0.11505457, 0.60906654, 0.13339096, 0.24058962, 0.32713906])

In [17]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [18]:
arr = np.arange(0,30)
arr.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [19]:
arr_random = np.random.randint(0,51,15)
arr_random

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2, 21,  1, 23, 43, 29],
      dtype=int32)

In [20]:
arr_random.max()

np.int32(43)

In [21]:
arr_random.min()

np.int32(1)

In [22]:
arr_random.argmax()

np.int64(13)

In [23]:
arr_random.argmin()

np.int64(11)

In [24]:
arr_random.dtype

dtype('int32')

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
arr.shape

(30,)

In [27]:
arr = arr.reshape()
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [28]:
arr.shape

(6, 5)

In [29]:
np.linspace()

TypeError: linspace() missing 2 required positional arguments: 'start' and 'stop'