In [2]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[10]

np.int64(10)

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5] = 50
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_array = arr[:5]
slice_of_array

array([50, 50, 50, 50, 50])

In [16]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr = np.arange(0,11)
arr_copy = arr.copy()
arr_copy[:] = 99
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[2,1]

np.int64(40)

In [35]:
arr_2d[:2,1:3]

""" or """

arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])