In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
np.log(arr)

C:\Users\PREDATOR HELIOS\AppData\Local\Temp\ipykernel_64744\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
arr.sum()

np.int64(45)

In [14]:
arr.mean()

np.float64(4.5)

In [16]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
arr_2d.shape

(5, 5)

In [20]:
arr_2d.sum(axis=0) ##Y position 

array([50, 55, 60, 65, 70])

In [21]:
arr_2d.sum(axis=1) ## X Position

array([ 10,  35,  60,  85, 110])